[tool.coverage.run]
concurrency = ["thread", "multiprocessing"]
parallel = true
sigterm = true

[tool.ruff]
exclude = [
    "__init__.py",
]
line-length = 119
required-version = "==0.12.0"
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "YTT", "LOG"]
ignore = ["E501", "E702", "E731"]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.isort]
known-local-folder = ["static"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
